### ISSUE TITLE
Broekn link - https://files.ipd.uw.edu/pub/RoseTTAFold/pdb100_2021Mar03.tar.gz

### ISSUE THREAD

**Issue by YaronBSG** [uw-ipd/RoseTTAFold2NA#10]
The link in the README is down:
# structure templates (including *_a3m.ffdata, *_a3m.ffindex)
wget https://files.ipd.uw.edu/pub/RoseTTAFold/pdb100_2021Mar03.tar.gz

**Comment by fdimaio** [comment]
There was some brief downtime on our file server.  It should be good now.
