### ISSUE TITLE
bug fix on convert "U" to "T"

### ISSUE THREAD

**Issue by qiyubio** [uw-ipd/RoseTTAFold2NA#15]
Hi, I think there is a bug on this line:
https://github.com/uw-ipd/RoseTTAFold2NA/commit/0f697067bf41b3d4e918caa3f65803a5c6047733#diff-dbc96069aed7abb32833a00cfcfe2143b53f06a12b01a3ed7f7ec98a44cf239dR116
An easy fix would be:
msa[msa == ord("U")] = 30

**Comment by fdimaio** [comment]
good catch!

**Comment by bifxcore** [comment]
Would it be possible to push the fix to the main branch? I installed the package according to the instructions on the README and that checks out the old version with the bug... would have been nice to avoid a crash after the MSA took 14hrs to complete ;-)
