### ISSUE TITLE
Downloading the RNA database according to README instructions

### ISSUE THREAD

**Issue by smturzo** [uw-ipd/RoseTTAFold2NA#17]
In the README for downloading the RNA databases, there maybe a small typo:
When I do wget with the flag -C  (as shown below) I get invalid option. Should this be lowercase "c" for all??:
wget ftp://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/Rfam.cm.gz -C ./RNA
wget: invalid option -- 'C'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
(RF2NA) [osu10269@pitzer-login04 RoseTTAFold2NA]$ wget ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/sequences/rnacentral_species_specific_ids.fasta.gz -C ./RNA
wget: invalid option -- 'C'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
(RF2NA) [osu10269@pitzer-login04 RoseTTAFold2NA]$ wget ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/rfam/rfam_annotations.tsv.gz -C ./RNA
wget: invalid option -- 'C'
Usage: wget [OPTION]... [URL]...

**Comment by fdimaio** [comment]
Sorry!  The installation instructions have been fixed.
