### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by S-m-Baffoe** [uw-ipd/RoseTTAFold2NA#2]
Hi,
I think your repo is locked
can you make it accessible for cloning

**Comment by dominik-handler** [comment]
The repo-link in the Readme is wrong. It worked for me by getting the link for cloning myself from the Github page. 
Another mistake is in the usage section. The conda environment is called RF2NA and not only RF2 as stated down there.

**Comment by fdimaio** [comment]
Thanks!  I have fixed the link and environment in the README
