### ISSUE TITLE
what is version.txt.gz and how can we find it?

### ISSUE THREAD

**Issue by YaoYinYing** [uw-ipd/RoseTTAFold2NA#3]
Hi!
Thank you for the fantastic work! 

I saw this line 
https://github.com/uw-ipd/RoseTTAFold2NA/blob/9acb073111f1593300e81129f261600ef40e656e/README.md?plain=1#L56

What is that file? and how can we find it?

**Comment by fdimaio** [comment]
Sorry!  That file is not needed.  I will remove from the README
