### ISSUE TITLE
RNA alphabet error

### ISSUE THREAD

**Issue by mpacella88** [uw-ipd/RoseTTAFold2NA#4]
Incredible work! Thanks so much for sharing! I've been encountering a PyTorch error when using RNA sequences that contain "U". I think I've traced it to network/parsers.py line 104: shouldn't the rna_alphabet contain U instead of T?

**Comment by fdimaio** [comment]
Hello, This is due to the fact that our RNA MSA generation pipeline produces 'T's.  I will check in a fix so it recognizes either.
