### ISSUE TITLE
Issue with using BLAST

### ISSUE THREAD

**Issue by huangtinglin** [uw-ipd/RoseTTAFold2NA#56]
Hello! Thanks for this great work which helps me a lot!

I am using RoseTTAFold2NA for the prediction of protein and RNA complexes. However, I am facing an error in constructing the MSA of the RNA. The issue arises when the program attempts to execute this [command](https://github.com/uw-ipd/RoseTTAFold2NA/blob/main/input_prep/make_rna_msa.sh#L91). The following error message is returned:

`BLAST Database error: No alias or index file found for nucleotide database [/home/huangtin/RoseTTAFold2NA/RNA/] in search path [/home/huangtin/RoseTTAFold2NA/aptamer_data/test/rna_pred::]
`

It appears that BLAST is unable to locate the index file of the 'nt' database, even though it has been downloaded. The RNA sequence I am utilizing is GCUUCUGGACUGCGAUGGGAGCACGAAACGUCGUGGCGCAAUUGGGUGGGGAAAGUCCUUAAAAGAGGGCCACCACAGAAGC.

I would appreciate any assistance in resolving this issue. Thanks!

**Comment by fglaser** [comment]
Same issue here, it seems specific for a certain sequence or RNA, changing the RNA with the same protein it works. Even when I add some nucleotides to the original sequence I need it works. This is the error and sequence I am using:

> RNA
UUGAGACGGAGUCUCGCUCUG


::::::::::::::
rna_pred.3/log/make_msa.RNA.yael.1.stderr
::::::::::::::
/home/rosetta2na/RoseTTAFold2NA/input_prep/make_rna_msa.sh: line 9: [: missing `]'

Error: Failed to open binary auxfiles for /data/databases/rosetta2na/RNA/Rfam.cm: use cmpress first

grep: cmscan.tblout: No such file or directory
rm: cannot remove 'cmscan.out': No such file or directory
rm: cannot remove 'cmscan.tblout': No such file or directory
rm: cannot remove 'rfam1.list.split.*': No such file or directory
rm: cannot remove 'rfam2.list.split.*': No such file or directory

**BLAST Database error: No alias or index file found for nucleotide database [/data/databases/rosetta2na/RNA] in search path [/home/rosetta2na/RoseTTAFold2NA/example/rna_pred.3::]**

rm: cannot remove 'blastn2.list.split.*': No such file or directory
grep: db: No such file or directory
rm: cannot remove 'cdhitest2d.db': No such file or directory
rm: cannot remove 'cdhitest2d.db.clstr': No such file or directory
rm: cannot remove 'db.clstr': No such file or directory

**Comment by fglaser** [comment]
Seems to me a minimal lenght issue?
When I add 4-5 GGGGG to the beginning or to the end of the sequence (20 bases) it works perfectly oK.
