### ISSUE TITLE
weights size mismatch

### ISSUE THREAD

**Issue by heejongkim** [uw-ipd/RoseTTAFold2NA#6]
Hi,

Appreciate such awesome work!

I just bump into the size difference of weights issue between what i got and what it should be.
From the README, it should be 1.6G but I only see a shy 800M.
I used the same path to download and i saw that wget reached to 100%.
Whenever you have a chance, can you please take a quick look at it? 

Thank you.

best,
heejong

**Comment by fdimaio** [comment]
Sorry!  That's a mistake in the README!

**Comment by heejongkim** [comment]
gotcha.
thank you for the clarification and quick fix.

best,
heejong
