### ISSUE TITLE
Issue when running on GPU

### ISSUE THREAD

**Issue by retiro** [uw-ipd/RoseTTAFold2NA#60]
Hi,

after strictly following the installation instructions, I activated RF2NA conda environment, positioned in the example folder and ran the RNA structure prediction by executing the following instruction:

`../run_RF2NA.sh rna_pred R:RNA.fa`

After running the rMSA, RNA.afa appears in the rna_pred folder. Afterward, it says: _Running on GPU_ and after a while the execution stops saying:

`           plddt    best`
`../run_RF2NA.sh: line 131: 3899038 Floating point exception(core dumped) python $PIPEDIR/network/predict.py -inputs $argstring -prefix $WDIR/models/model -model $PIPEDIR/network/weights/RF2NA_apr23.pt -db $HHDB`

After debugging, it seems that the problem is somewhere in SE3Transformer, but I could not figure it out.

Has anyone encountered the same issue or does it seem familiar to you?

Thanks.

**Comment by VincentQTran** [comment]
did you figure out what the solution was to this Floating point exception?

**Comment by Huang-XN** [comment]
Same question
