### ISSUE TITLE
possible mistake in make_rna_msa.sh

### ISSUE THREAD

**Issue by DimaMolod** [uw-ipd/RoseTTAFold2NA#7]
First of all thanks for the great work!

I think we might have found a mistake in [input_prep/make_rna_msa.sh:](https://github.com/uw-ipd/RoseTTAFold2NA/blob/main/input_prep/make_rna_msa.sh) (line 126)
```
for e_val in 1e-8, 1e-7, 1e-6, 1e-3, 1e-2, 1e-1
do
    nhmmer --noali -A nhmmer.a2m --incE $e_val --cpu $CPU --watson $in_fasta db | grep 'no alignment saved'
    ...
done
```
the loop here is wrong: this will pass 1e-8, etc (including the comma in the end) to nhummer but it will work only for 1e-1 which doesn't have a coma in the end. For the rest of values nhummer throws an error message which is hidden by the grep command.

**Comment by fdimaio** [comment]
Good catch!  It's now fixed.

**Comment by qiyubio** [comment]
Thanks for fix the bug. Although I'm having another error of no ```nhmmer.afa``` generated with the example input. Even though it does not seem to impact the next step, but is it expected? 

The error is
```grep: nhmmer.afa: No such file or directory```

**Comment by qiyubio** [comment]
Is the nhmmer.afa suppose to be $out_tag.afa? 
https://github.com/uw-ipd/RoseTTAFold2NA/blob/0f697067bf41b3d4e918caa3f65803a5c6047733/input_prep/make_rna_msa.sh#L131
