### ISSUE TITLE
where is update_blastdb.pl ?

### ISSUE THREAD

**Issue by JiayouZhang** [uw-ipd/RoseTTAFold2NA#75]
In readme.md:
```
# nt [151G]
update_blastdb.pl --decompress nt
cd ..
```

But I can't find `update_blastdb.pl`.

**Comment by denizkavi** [comment]
I was able to retrieve it from here: [https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/app/blast/update_blastdb.pl](https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/app/blast/update_blastdb.pl)
I'm not sure if this is how the authors intended it, but most scripts not found in the repo can be found through searching on Google.

**Comment by JiayouZhang** [comment]
It turns out that when you install the dependencies of the repo, `update_blastdb.pl` is downloaded in you conda environment:

```bash
which update_blastdb.pl 
/path-to-miniconda3/envs/env-name/bin/update_blastdb.pl
```

**Comment by ShuZishan** [comment]
Why is the nt dataset downloaded from this link https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/ larger [378GB] compared to the one downloaded using the command `update_blastdb.pl --decompress nt` [151GB]? Why are there differences between the two downloads? Could you provide details on the specific data that has been added or removed, and the reasons for these changes? I would greatly appreciate it.
